[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True

[mypy-grpc.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-prometheus_client.*]
ignore_missing_imports = True
