kind: CronJob
apiVersion: batch/v1
metadata:
  name: arag-downloads-cronjob
  labels:
    app: "{{ .Chart.Name }}"
    version: "{{ .Values.hash }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- with .Values.cronjobs.downloads.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    metadata:
      name: arag-downloads-cronjob
      labels:
        app: arag
        role: cronjobs
        version: "{{ .Values.hash }}"
        chart: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      backoffLimit: 0
      template:
        metadata:
          {{- with .Values.cronjobs.downloads.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            app: arag
            role: cronjobs
            version: "{{ .Values.hash }}"
            chart: "{{ .Chart.Name }}"
            release: "{{ .Release.Name }}"
        spec:
          serviceAccountName: {{ if kindIs "string" .Values.cronjobs.downloads.serviceAccount }}{{ .Values.cronjobs.downloads.serviceAccount }}{{ else }}{{ .Values.cronjobs.downloads.serviceAccount.name | default "default" }}{{ end }}
          nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
          topologySpreadConstraints:
{{ toYaml .Values.topologySpreadConstraints | indent 12 }}
          affinity:
{{ toYaml .Values.affinity | indent 12 }}
          tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
          dnsPolicy: ClusterFirst
{{- with .Values.priorityClassName }}
          priorityClassName: {{ . }}
{{- end }}
          restartPolicy: Never
          containers:
          - name: arag-downloads-cronjob
            image: "{{ .Values.containerRegistry }}/{{ .Values.image.aragServer }}:{{ .Values.image.tag }}"
            {{- with .Values.envFrom }}
            envFrom:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.env}}
            env:
              {{- include "toEnv" . | indent 14 }}
            {{- end }}
            imagePullPolicy: IfNotPresent
            {{- with .Values.cronjobs.downloads.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end}}
            command:
            - arag-downloads-cronjob
