kind: Service
apiVersion: v1
metadata:
  name: arag-api
  labels:
    app: arag-api
    version: "{{ .Values.hash }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  selector:
    app: arag-api
  {{- with .Values.api.service.ports }}
  ports:
{{ toYaml . | indent 4 }}
  {{- end }}