apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: arag-api
  labels:
    app: arag-api
    version: "{{ .Values.hash }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: arag-api
  minReplicas: {{.Values.api.minReplicas}}
  maxReplicas: {{.Values.api.maxReplicas}}
  metrics: {{- toYaml .Values.api.metrics | nindent 4}}
