apiVersion: batch/v1
kind: Job
metadata:
  name: nucliadb-agentic-migrate
  labels:
    app: nucliadb-agentic-migrate
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}"
    version: "{{ .Values.hash }}"
  {{- with .Values.migrations.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      name: nucliadb-agentic-migrate
      {{- with .Values.migrations.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: nucliadb-agentic-migrate
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}"
        version: "{{ .Values.hash }}"
    spec:
      restartPolicy: Never
{{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
{{- end }}
      serviceAccountName: {{ if kindIs "string" .Values.migrations.serviceAccount }}{{ .Values.migrations.serviceAccount }}{{ else }}{{ .Values.migrations.serviceAccount.name | default "default" }}{{ end }}
      containers:
      - name: pre-upgrade-job
        image: "{{ .Values.containerRegistry }}/{{ .Values.image.nucliadbAgenticApi }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ["cd /app/nucliadb-agentic && alembic upgrade head"]
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
          - name: VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['version']
          {{- include "toEnv" .Values.env | indent 10 }}