apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nucliadb-agentic-server
  labels:
    app: nucliadb-agentic-server
    version: "{{ .Values.hash }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nucliadb-agentic-server
  minReplicas: {{.Values.server.minReplicas}}
  maxReplicas: {{.Values.server.maxReplicas}}
  metrics: {{- toYaml .Values.server.metrics | nindent 4}}
