containerRegistry: europe-west4-docker.pkg.dev/nuclia-internal/nuclia

image:
  nucliadbAgenticApi: nucliadb-agentic
  nucliadbAgenticServer: nucliadb-agentic
  tag: TAG_TO_REPLACE

hash: "HASH_VERSION_TO_REPLACE" # Use quotes to force string due https://github.com/kubernetes-sigs/yaml/issues/45

env:
  ZONE: provider-region-ordinal
  RUNNING_ENVIRONMENT: stage

  NATS_HOST: nats://nats-regional.nats-regional.svc:4222

  STATS_SUBJECT: "training_stats"
  IDP_ADDRESS: "idp-grpc.idp-regional.svc.cluster.local:9090"

  LEARNING_CONFIG_GRPC: "config.learning.svc.cluster.local:8030"

  HTTP_PORT: 8080
  GRPC_PORT: 8030

  INTERNAL_NUA_API: "http://predict.learning.svc.cluster.local:8080"
  INTERNAL_NUA: True

  INTERNAL_NUCLIADB: True
  INTERNAL_NUCLIADB_URL: "{component}.nucliadb.svc.cluster.local:8080"
  ## Secrets values. Currently not used as they are set through envFrom
  # POSTGRESQL_DSN:
  #   valueFrom:
  #     secretKeyRef:
  #       name: nucliadb-agentic-secrets
  #       key: nucliadb-agentic.POSTGRESQL_DSN
  # SENTRY_URL:
  #   valueFrom:
  #     secretKeyRef:
  #       name: nucliadb-agentic-secrets
  #       key: nucliadb-agentic.SENTRY_URL

nats_secret:  # Secret name containing nats creds to mount
tracing:
  enabled: false

zone: provider-region-ordinal
vs:
  gateway: "istio-system/xxxxxx"
  host: "xxxxx.cloud"

api:
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  annotations: {}
  securityContext: {}
  revisionHistoryLimit: 2
  minReplicas: 2
  maxReplicas: 6
  ports:
    - name: http
      containerPort: 8080
    - name: grpc-port
      containerPort: 8030
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
  resources:
    requests:
      cpu: "300m"
      memory: "600Mi"
  service:
    ports:
      - name: http
        port: 8080
      - name: grpc-port
        port: 8030
  serviceAccount:
    create: false
    name: default
    labels: {}
    annotations: {}
  serviceMonitor:
    enabled: false
    port: http
    interval: 60s

server:
  annotations: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  revisionHistoryLimit: 2
  minReplicas: 2
  maxReplicas: 6
  ports:
    - name: metrics
      containerPort: 8090
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
  resources:
    requests:
      cpu: "300m"
      memory: "600Mi"
  securityContext: {}
  service:
    ports:
      - name: metrics
        port: 8090
  serviceAccount:
    create: false
    name: default
    labels: {}
    annotations: {}
  serviceMonitor:
    enabled: false
    port: metrics
    interval: 60s

  sandbox:
    enabled: true
    uid: 53478
    socket_mount: /sandbox-socket
    iptablesImage: "iptables"
    iptablesVersion: "latest"
    ports:
      - name: sandbox-metrics
        containerPort: 8091
    serviceMonitor:
      enabled: false
      port: sandbox-metrics
      interval: 60s

extraContainers: []

migrations:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  serviceAccount:
    create: false
    name: default
    labels: {}
    annotations: {}


cronjobs:
  downloads:
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
    annotations: {}
    podAnnotations: {}
    serviceAccount:
      create: false
      name: default
      labels: {}
      annotations: {}
  workflowsCleanup:
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
    annotations: {}
    podAnnotations: {}
    serviceAccount:
      create: false
      name: default
      labels: {}
      annotations: {}
