[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hyperforge_nucliadb_agentic"
version = "1.0.0"
license = "Apache-2.0"
description = "NucliaDB Hyperforge agent"
authors = [{ name = "Nuclia", email = "nucliadb@nuclia.com" }]
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10, <4"
dependencies = ["hyperforge", "lingua-language-detector", "nucliadb_sdk"]

[dependency-groups]
# these dependencies are actually in the src/ folder (under
# src/nucliadb_utils/tests/), but only used when the module is imported
dev = [
    "pytest",
    "pytest-benchmark",
    "pytest-docker-fixtures>=1.4.2",
    "pytest-lazy-fixtures",
    "hyperforge_rephrase",
]

[project.urls]
Homepage = "https://progress.com"
Repository = "https://github.com/nuclia/nucliadb_agentic_api"
Changelog = "https://github.com/nuclia/nucliadb_agentic_api/blob/main/agents/nucliadb/CHANGELOG.md"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.uv.build-backend]

# Exclude specific files from being packaged
source-exclude = ["tests/**", "*.pyc"]
