name: NucliaDB Agents Tests

on:
    push:
        branches:
            - main
            - dev
        paths:
            - "agents/nucliadb/**"
            - "hyperforge.mk"
            - ".github/workflows/hyperforge_nucliadb_agentic.yaml"
    pull_request:
        branches:
            - main
            - dev
        paths:
            - "agents/nucliadb/**"
            - "hyperforge.mk"
            - ".github/workflows/hyperforge_nucliadb_agentic.yaml"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    test:
        name: Test agents/nucliadb
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
              with:
                  enable-cache: false
                  python-version: "3.12"

            - name: Install package dependencies with uv
              run: uv sync --group dev

            - name: Run tests
              working-directory: agents/nucliadb
              run: make test
              env: # Or as an environment variable
                  NUA_KEY: ${{ secrets.NUA_KEY }}
                  HEALTH_CHECK_PORT: 8099
    build_wheels:
        name: Build wheels
        runs-on: ubuntu-24.04
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        needs:
            - test
        environment: pypi
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
              with:
                  enable-cache: false
                  python-version: "3.12"

            - name: Set dependency versions in requirements
              run: |
                  python bump.py --package=${INPUTS_PACKAGE} --build=${{ github.run_number }}
              env:
                  INPUTS_PACKAGE: agents/nucliadb

            - name: Build wheels
              run: uv build ./${INPUTS_PACKAGE}
              env:
                  INPUTS_PACKAGE: agents/nucliadb

            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
