name: NucliaDB Agentic API Tests

on:
    push:
        branches:
            - main
            - dev
        paths:
            - "**"
            - ".github/workflows/nucliadb_agentic_api_workflow.yaml"
            - "NUCLIADB_AGENTIC_API.Dockerfile"
    pull_request:
        branches:
            - main
            - dev
        paths:
            - "**"
            - ".github/workflows/nucliadb_agentic_api_workflow.yaml"
            - "NUCLIADB_AGENTIC_API.Dockerfile"
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

env:
    GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/224545243904/locations/global/workloadIdentityPools/gh-nuclia/providers/gh-nuclia-provider"
    GCP_SERVICE_ACCOUNT: "github-actions@nuclia-internal.iam.gserviceaccount.com"

permissions:
    id-token: write
    contents: read
    actions: read
    packages: write

jobs:
    test:
        name: Testing
        runs-on: ubuntu-latest
        outputs:
            component: ${{ steps.param.outputs.component }}
            hash: ${{ steps.param.outputs.hash }}
            branch: ${{ steps.param.outputs.branch }}
            component-version: ${{ steps.param.outputs.component-version }}
            img-version: ${{ steps.param.outputs.img-version }}
            chart-version: ${{ steps.param.outputs.chart-version }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                persist-credentials: false

            - name: Generate a token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                app-id: ${{ secrets.GHAPP_ID_NUCLIABOT }}
                private-key: ${{ secrets.PK_GHAPP_NUCLIABOT }}
                owner: nuclia
                repositories: tooling
                permission-contents: read

            - name: Checkout tooling repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                repository: nuclia/tooling
                ref: main
                path: tooling
                token: ${{ steps.app-token.outputs.token }}
                persist-credentials: false

            - name: Parameter generator
              uses: ./tooling/.github/actions/parameter-generator
              id: param
              with:
                  component: nucliadb-agentic
                  helm-separator: "-ref"

            - name: Install uv
              uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

            - name: Install package
              run: uv sync
              env:
                  PYTHONUNBUFFERED: 1

            - name: Lint package
              run: |
                  make lint

            - name: Test package
              run: |
                  make  test
