name: NucliaDB Agentic API Tests

on:
    push:
        branches:
            - main
            - dev
        paths:
            - "**"
            - ".github/workflows/nucliadb_agentic_api_workflow.yaml"
            - "NUCLIADB_AGENTIC_API.Dockerfile"
    pull_request:
        branches:
            - main
            - dev
        paths:
            - "**"
            - ".github/workflows/nucliadb_agentic_api_workflow.yaml"
            - "NUCLIADB_AGENTIC_API.Dockerfile"
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
    cancel-in-progress: true

env:
    GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/224545243904/locations/global/workloadIdentityPools/gh-nuclia/providers/gh-nuclia-provider"
    GCP_SERVICE_ACCOUNT: "github-actions@nuclia-internal.iam.gserviceaccount.com"

permissions:
    id-token: write
    contents: read
    actions: read
    packages: write

jobs:
    test:
        name: Testing
        runs-on: ubuntu-latest
        outputs:
            component: ${{ steps.param.outputs.component }}
            hash: ${{ steps.param.outputs.hash }}
            branch: ${{ steps.param.outputs.branch }}
            component-version: ${{ steps.param.outputs.component-version }}
            img-version: ${{ steps.param.outputs.img-version }}
            chart-version: ${{ steps.param.outputs.chart-version }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Generate a token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                  client-id: ${{ secrets.GHAPP_ID_NUCLIABOT }}
                  private-key: ${{ secrets.PK_GHAPP_NUCLIABOT }}
                  owner: nuclia
                  repositories: tooling
                  permission-contents: read

            - name: Checkout tooling repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  repository: nuclia/tooling
                  ref: main
                  path: tooling
                  token: ${{ steps.app-token.outputs.token }}
                  persist-credentials: false

            - name: Parameter generator
              uses: ./tooling/.github/actions/parameter-generator
              id: param
              with:
                  component: nucliadb-agentic
                  helm-separator: "-ref"
                  folder: src/nucliadb_agentic_api

            - name: Install uv
              uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

            - name: Install package
              run: uv sync
              env:
                  PYTHONUNBUFFERED: 1

            # - name: Lint package
            #   run: |
            #       make lint

            # - name: Test package
            #   run: |
            #       make test
            #   env:
            #       NUA_KEY: ${{ secrets.NUA_KEY }}
            #       HEALTH_CHECK_PORT: 8099
    # build_wheels:
    #     name: Build wheels
    #     runs-on: ubuntu-24.04
    #     if: github.event_name == 'push'
    #     needs:
    #         - test
    #     permissions:
    #         contents: read
    #         id-token: write
    #     steps:
    #         - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    #           with:
    #               persist-credentials: false

    #         - name: Install uv
    #           uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    #           with:
    #               enable-cache: false
    #               python-version: "3.12"

    #         - name: Setup env
    #           run: |
    #               uv tool install twine

    #         - name: Set dependency versions in requirements
    #           run: |
    #               python bump.py --package=${INPUTS_PACKAGE} --build=${{ github.run_number }}
    #           env:
    #               INPUTS_PACKAGE: .

    #         - name: Install package
    #           run: |
    #               uv sync

    #         - name: Build wheels
    #           run: uv build ./${INPUTS_PACKAGE}
    #           env:
    #               INPUTS_PACKAGE: .

    #         - name: Publish package to PyPI
    #           uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

    # build_and_push_docker_image:
    #     name: Build and push Docker image
    #     runs-on: ubuntu-24.04
    #     if: github.event_name == 'push'
    #     needs:
    #         - build_wheels
    #     permissions:
    #         contents: read
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    #           with:
    #               persist-credentials: false

    #         - name: Log in to GitHub Container Registry
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #               GITHUB_ACTOR: ${{ github.actor }}
    #           run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin

    #         - name: Build Docker image
    #           env:
    #               REPOSITORY_OWNER: ${{ github.repository_owner }}
    #               IMAGE_SHA_TAG: ${{ github.sha }}
    #               IMAGE_REF_TAG: ${{ github.ref_name }}
    #           run: docker build -f NUCLIADB_AGENTIC_API.Dockerfile -t "ghcr.io/$REPOSITORY_OWNER/nucliadb_agentic_api:$IMAGE_SHA_TAG" -t "ghcr.io/$REPOSITORY_OWNER/nucliadb_agentic_api:$IMAGE_REF_TAG" .

    #         - name: Push Docker image
    #           env:
    #               REPOSITORY_OWNER: ${{ github.repository_owner }}
    #               IMAGE_SHA_TAG: ${{ github.sha }}
    #               IMAGE_REF_TAG: ${{ github.ref_name }}
    #           run: |
    #               docker push "ghcr.io/$REPOSITORY_OWNER/nucliadb_agentic_api:$IMAGE_SHA_TAG"
    #               docker push "ghcr.io/$REPOSITORY_OWNER/nucliadb_agentic_api:$IMAGE_REF_TAG"
    
    build_and_push_internal:
        name: Build and push internal Docker image
        runs-on: nuclia-base
        needs:
            - test
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Generate a token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                client-id: ${{ secrets.GHAPP_ID_NUCLIABOT }}
                private-key: ${{ secrets.PK_GHAPP_NUCLIABOT }}
                owner: nuclia

            - name: Checkout tooling repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                repository: nuclia/tooling
                ref: main
                path: tooling
                token: ${{ steps.app-token.outputs.token }}

            - name: Authenticate to Google Cloud
              id: gcp-auth
              uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 #v3
              with:
                workload_identity_provider: "${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
                service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"
                token_format: access_token

            - name: Login to Google Artifact Registry
              uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
              with:
                registry: europe-west4-docker.pkg.dev
                username: oauth2accesstoken
                password: ${{ steps.gcp-auth.outputs.access_token }}

            - name: Build and Push image to registries
              uses: ./tooling/.github/actions/build-img-regcache
              with:
                file: NUCLIADB_AGENTIC_API.Dockerfile
                image-name: ${{ needs.test.outputs.component }}
                image-version: ${{ needs.test.outputs.img-version }}
                aws-ecr-role: ${{ secrets.AWS_ECR_ROLE }}
                tag-latest: ${{ github.ref == 'refs/heads/main' && 'latest' || 'dev-latest' }}
                push: true
                ghapp-nuclia-service-bot-id: ${{ secrets.GHAPP_ID_NUCLIABOT }}
                ghapp-nuclia-service-bot-pk: ${{ secrets.PK_GHAPP_NUCLIABOT }}
